# Generated by Django 2.1.7 on 2019-03-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='FirstName',
            field=models.CharField(default='First Name', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='LastName',
            field=models.CharField(default='Last Name', max_length=20),
        ),
    ]
